// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package org.pgg.domain;

import org.pgg.domain.Foo;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect Foo_Roo_Configurable {
    
    declare @type: Foo: @Configurable;
    
}
