// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package org.pgg.domain;

import org.pgg.domain.Foo;

privileged aspect Foo_Roo_JavaBean {
    
    public String Foo.getBar() {
        return this.bar;
    }
    
    public void Foo.setBar(String bar) {
        this.bar = bar;
    }
    
}
